export function getDomElements() {
  return {
    app: document.getElementById("app"),
    canvas: document.getElementById("game"),
    hud: document.getElementById("hud"),
    startScreen: document.getElementById("start-screen"),
    betScreen: document.getElementById("bet-screen"),
    betCountdown: document.getElementById("bet-countdown"),
    introSummary: document.getElementById("intro-summary"),
    introSkipBtn: document.getElementById("intro-skip-btn"),
    thanosScreen: document.getElementById("thanos-screen"),
    tenFightScreen: document.getElementById("ten-fight-screen"),
    tenFightTitle: document.getElementById("ten-fight-title"),
    tenFightSubtext: document.getElementById("ten-fight-subtext"),
    tenFightBar: document.getElementById("ten-fight-bar"),
    tenFightBarFill: document.getElementById("ten-fight-bar-fill"),
    tenFightTime: document.getElementById("ten-fight-time"),
    resultScreen: document.getElementById("result-screen"),
    settingsPanel: document.getElementById("settings-panel"),
    brandMark: document.getElementById("brand-mark"),
    brandSubtitle: document.getElementById("brand-subtitle"),
    startBtn: document.getElementById("start-btn"),
    roomBtn: document.getElementById("room-btn"),
    restartBtn: document.getElementById("restart-btn"),
    nextRoundBtn: document.getElementById("next-round-btn"),
    reportBtn: document.getElementById("report-btn"),
    reportScreen: document.getElementById("report-screen"),
    reportClose: document.getElementById("report-close"),
    reportText: document.getElementById("report-text"),
    reportChart: document.getElementById("report-chart"),
    reportMvp: document.getElementById("report-mvp"),
    roomScreen: document.getElementById("room-screen"),
    roomExit: document.getElementById("room-exit"),
    roomNamePanel: document.getElementById("room-name-panel"),
    roomStatus: document.getElementById("room-status"),
    roomNameInput: document.getElementById("room-name-input"),
    roomCodeInput: document.getElementById("room-code-input"),
    roomNameConfirm: document.getElementById("room-name-confirm"),
    roomBettingPanel: document.getElementById("room-betting-panel"),
    roomCountdown: document.getElementById("room-countdown"),
    roomCodeBadge: document.getElementById("room-code-badge"),
    roomPresetTitle: document.getElementById("room-preset-title"),
    roomMechanics: document.getElementById("room-mechanics"),
    roomPicks: [...document.querySelectorAll("[data-room-pick]")],
    roomPickStatus: document.getElementById("room-pick-status"),
    roomLeaderboard: document.getElementById("room-leaderboard"),
    roomSettlePanel: document.getElementById("room-settle-panel"),
    roomSettleEmoji: document.getElementById("room-settle-emoji"),
    roomSettleTitle: document.getElementById("room-settle-title"),
    roomSettleDetail: document.getElementById("room-settle-detail"),
    roomSettleCountdown: document.getElementById("room-settle-countdown"),
    roomSettleBoard: document.getElementById("room-settle-board"),
    roomWatchBar: document.getElementById("room-watch-bar"),
    roomWatchStatus: document.getElementById("room-watch-status"),
    roomRankToggle: document.getElementById("room-rank-toggle"),
    roomRankPanel: document.getElementById("room-rank-panel"),
    roomWatchBoard: document.getElementById("room-watch-board"),
    pauseToggle: document.getElementById("pause-toggle"),
    homeBtn: document.getElementById("home-btn"),
    godHandToggle: document.getElementById("god-hand-toggle"),
    settingsToggle: document.getElementById("settings-toggle"),
    settingsClose: document.getElementById("settings-close"),
    soundToggle: document.getElementById("sound-toggle"),
    pushTool: document.getElementById("push-tool"),
    pullTool: document.getElementById("pull-tool"),
    eventFeed: document.getElementById("event-feed"),
    bettingControls: document.getElementById("betting-controls"),
    tournamentControls: document.getElementById("tournament-controls"),
    score: [
      document.getElementById("s-rock"),
      document.getElementById("s-scissors"),
      document.getElementById("s-paper"),
    ],
    odds: [
      document.getElementById("odds-rock"),
      document.getElementById("odds-scissors"),
      document.getElementById("odds-paper"),
    ],
    roundIndex: document.getElementById("round-index"),
    roundTotal: document.getElementById("round-total"),
    matchScore: document.getElementById("match-score"),
    timer: document.getElementById("timer"),
    bank: document.getElementById("bank"),
    winnerEmoji: document.getElementById("winner-emoji"),
    winnerText: document.getElementById("winner-text"),
    winnerSubtext: document.getElementById("winner-subtext"),
    nextBetPanel: document.getElementById("next-bet-panel"),
    nextStake: document.getElementById("next-stake"),
    inputs: {
      rock: document.getElementById("cfg-rock"),
      scissors: document.getElementById("cfg-scissors"),
      paper: document.getElementById("cfg-paper"),
      names: [
        document.getElementById("cfg-name-0"),
        document.getElementById("cfg-name-1"),
        document.getElementById("cfg-name-2"),
      ],
      syncCounts: document.getElementById("cfg-sync-counts"),
      duration: document.getElementById("cfg-duration"),
      bgmVolume: document.getElementById("cfg-bgm-volume"),
      sfxVolume: document.getElementById("cfg-sfx-volume"),
      notifications: document.getElementById("cfg-notifications"),
      liveBgmVolume: document.getElementById("live-bgm-volume"),
      liveSfxVolume: document.getElementById("live-sfx-volume"),
      liveNotifications: document.getElementById("live-notifications"),
      stake: document.getElementById("cfg-stake"),
      penalty: document.getElementById("cfg-penalty"),
      betting: document.getElementById("opt-betting"),
      tournament: document.getElementById("opt-tournament"),
      deathmatch: document.getElementById("opt-deathmatch"),
      zones: document.getElementById("opt-zones"),
      godHand: document.getElementById("opt-god-hand"),
      obstacles: document.getElementById("opt-obstacles"),
      shrink: document.getElementById("opt-shrink"),
      bounty: document.getElementById("opt-bounty"),
      traitor: document.getElementById("opt-traitor"),
      blackHole: document.getElementById("opt-black-hole"),
      powerups: document.getElementById("opt-powerups"),
      tenFight: document.getElementById("opt-ten-fight"),
      lastStand: document.getElementById("opt-last-stand"),
      thanos: document.getElementById("opt-thanos"),
    },
    nextOdds: [
      document.getElementById("next-odds-rock"),
      document.getElementById("next-odds-scissors"),
      document.getElementById("next-odds-paper"),
    ],
    presetButtons: [...document.querySelectorAll("[data-preset]")],
    countStepButtons: [...document.querySelectorAll("[data-count-step]")],
    themeButtons: [...document.querySelectorAll("[data-theme]")],
    setupSummaries: [...document.querySelectorAll("[data-setup-summary]")],
  };
}
