import { DEFAULT_ROUND_LIMIT } from "../config/constants.js";
import { THEMES } from "../config/themes.js";

export function createInitialState() {
  return {
    W: 0,
    H: 0,
    dpr: 1,
    entities: [],
    obstacles: [],
    powerUps: [],
    blackHoles: [],
    pendingTraitors: [],
    particles: [],
    running: false,
    paused: false,
    roundOver: false,
    suddenDeath: false,
    animId: 0,
    lastTs: 0,
    roundStart: 0,
    roundHoldUntil: 0,
    endOverlayTimer: 0,
    nextPowerAt: 0,
    nextTraitorAt: 0,
    nextBlackHoleAt: 0,
    traitorEarlyUsed: false,
    roundLimit: DEFAULT_ROUND_LIMIT,
    countdownTimer: 0,
    countdownTimers: [],
    theme: "rps",
    roundIndex: 1,
    bestOf: 3,
    wins: [0, 0, 0],
    penalties: [0, 0, 0],
    baseCounts: [10, 10, 10],
    customLabels: {
      colors: THEMES.colors.types.map((item) => item.label),
      countries: THEMES.countries.types.map((item) => item.label),
      brands: THEMES.brands.types.map((item) => item.label),
    },
    winnerPenalty: 5,
    bank: 1000,
    prediction: 0,
    stake: 100,
    odds: [2, 2, 2],
    lastBattleLog: [],
    bettingRoom: {
      active: false,
      online: false,
      phase: "idle",
      round: 0,
      roomCode: "",
      playerId: "",
      isHost: false,
      currentUser: "",
      selectedType: null,
      lockedType: null,
      currentPreset: null,
      autoTimer: 0,
      countdownTimer: 0,
      settleTimer: 0,
      syncTimer: 0,
      snapshotTimer: 0,
      syncedPhase: "",
      syncedRound: 0,
      startedRound: 0,
      settledRound: 0,
      lastResult: null,
      fixedStage: false,
      remoteSpectator: false,
      snapshotSeq: 0,
      lastSnapshotAt: 0,
      remoteFrameAt: 0,
    },
    settings: {
      bgmVolume: 0.45,
      sfxVolume: 0.8,
      notifications: true,
    },
    options: {
      betting: false,
      tournament: false,
      deathmatch: false,
      zones: false,
      godHand: false,
      obstacles: false,
      shrink: false,
      bounty: false,
      traitor: false,
      blackHole: false,
      powerups: false,
      tenFight: false,
      lastStand: false,
      thanos: false,
    },
    zones: {
      points: [],
      scores: [0, 0, 0],
    },
    bounty: {
      active: false,
      leader: null,
      lastLeader: null,
    },
    lastStand: {
      splitUsed: [false, false, false],
      reviveUsed: [false, false, false],
      pendingRevives: [],
      lastCounts: [0, 0, 0],
      lastPositions: [null, null, null],
    },
    arena: {
      padding: 0,
      targetPadding: 0,
      maxPadding: 0,
      hardMaxPadding: 0,
      lastShrink: 0,
      finalAt: 0,
      finalStarted: false,
    },
    pointer: {
      active: false,
      x: 0,
      y: 0,
      px: 0,
      py: 0,
      vx: 0,
      vy: 0,
      lastMove: -1000,
      mode: "push",
    },
    thanos: {
      nextAt: Infinity,
      warningAt: Infinity,
      active: false,
      applied: false,
      used: false,
      warned: false,
      snapAt: Infinity,
      hideAt: Infinity,
    },
    tenFight: {
      used: false,
      pending: false,
      active: false,
      minority: null,
      majority: null,
      checkAt: 0,
      freezeUntil: 0,
      startAt: 0,
      endAt: 0,
      overlayTimer: 0,
      lastKillAt: 0,
    },
  };
}
